name: Build profile banner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build-and-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Generate image
        run: node scripts/generate-image.js

      - name: Commit generated image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README-assets/profile-banner.png || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update profile banner image"
            git push origin HEAD:main
          fi