name: Generate Profile Banner

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12:00 UTC
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-banner:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3-dev \
          libatk-bridge2.0-dev \
          libdrm2 \
          libxkbcommon-dev \
          libgbm-dev \
          libasound2-dev \
          libatspi2.0-dev \
          libgtk-3-dev

    - name: Generate banner
      run: npm run generate-image

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README-assets/profile-banner.png
        git diff --staged --quiet || git commit -m "🎨 Update profile banner [automated]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: profile-banner
        path: README-assets/profile-banner.png
        retention-days: 30